/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Materia;
import Persistencia.MateriaData; 
import javax.swing.JOptionPane;
/**
 *
 * @author vanne
 */
public class BajaAltaMateria extends javax.swing.JInternalFrame {
    
    private MateriaData materiaData;
    private Materia materiaActual = null;
    /**
     * Creates new form BajaAltaMateria
     */
    
    public BajaAltaMateria(MateriaData md) { 
        this.materiaData = md;
        initComponents();
    }
    
    public BajaAltaMateria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBbuscar = new javax.swing.JButton();
        jBbaja = new javax.swing.JButton();
        jBalta = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 153));
        jLabel1.setText("Baja/Alta logica ");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("ID.Materia :");

        jBbuscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBbuscar.setText("Buscar");
        jBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarActionPerformed(evt);
            }
        });

        jBbaja.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBbaja.setText("Baja");
        jBbaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbajaActionPerformed(evt);
            }
        });

        jBalta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBalta.setText("Alta");
        jBalta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaltaActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jBbuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jBbaja, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jBalta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 143, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jBbaja, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jBalta, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBbuscar)
                    .addComponent(jBbaja)
                    .addComponent(jBalta))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBbajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbajaActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Obtener y validar el ID
            int id = Integer.parseInt(jTextField1.getText()); 
            
            // 2. Opcional, pero seguro: Verificar que la materia exista antes de la Baja
            Materia m = materiaData.buscarMateria(id); 

            if (m == null) {
                JOptionPane.showMessageDialog(this, "La materia con ID " + id + " no existe.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!m.getEstado()) { 
                JOptionPane.showMessageDialog(this, "La materia ya está INACTIVA (dada de baja).");
                return;
            }

            // 3. Llamar al método de persistencia
            materiaData.bajaMateria(id); 
            
            JOptionPane.showMessageDialog(this, "Materia ID " + id + " dada de BAJA correctamente.");
            jTextField1.setText("");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un ID válido.", "Error de formato", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al dar de baja: " + ex.getMessage(), "Error de BD", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBbajaActionPerformed

    private void jBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarActionPerformed
        // TODO add your handling code here:
        // 1. Validar que el campo no esté vacío
        if (jTextField1.getText().trim().isEmpty()) { 
            JOptionPane.showMessageDialog(this, "Debe ingresar el ID de la materia a buscar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // 2. Convertir y validar el ID
            int id = Integer.parseInt(jTextField1.getText());
            
            // 3. Buscar en la capa de persistencia
            Materia m = materiaData.buscarMateria(id); 
            
            if (m != null) {
                // Si la materia existe, la guardamos y mostramos el mensaje.
                materiaActual = m; 
                
                String estadoTexto = m.getEstado() ? "ACTIVA" : "INACTIVA";
                
                // 4. Mostrar el resultado completo
                JOptionPane.showMessageDialog(this, 
                        "Materia Encontrada:\n" +
                        "ID: " + m.getIdMateria() + "\n" +
                        "Nombre: " + m.getNombre() + "\n" +
                        "Estado Actual: " + estadoTexto + "\n\n" +
                        "Ahora puede presionar ALTA o BAJA.", 
                        "Búsqueda Exitosa", 
                        JOptionPane.INFORMATION_MESSAGE);
                        
            } else {
                // 5. Si no se encuentra
                materiaActual = null; 
                JOptionPane.showMessageDialog(this, "No existe ninguna materia con el ID: " + id, "Error de Búsqueda", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID debe ser un número entero válido.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBbuscarActionPerformed

    private void jBaltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaltaActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Obtener y validar el ID
            int id = Integer.parseInt(jTextField1.getText()); 
            
            // 2. Opcional, pero seguro: Verificar que la materia exista antes del Alta
            Materia m = materiaData.buscarMateria(id); 
            
            if (m == null) {
                JOptionPane.showMessageDialog(this, "La materia con ID " + id + " no existe.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (m.getEstado()) { 
                JOptionPane.showMessageDialog(this, "La materia ya está ACTIVA (dada de alta).");
                return;
            }
            
            // 3. Llamar al método de persistencia
            materiaData.altaMateria(id); 
            
            JOptionPane.showMessageDialog(this, "Materia ID " + id + " dada de ALTA correctamente.");
            jTextField1.setText("");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un ID válido.", "Error de formato", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al dar de alta: " + ex.getMessage(), "Error de BD", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBaltaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBalta;
    private javax.swing.JButton jBbaja;
    private javax.swing.JButton jBbuscar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
