/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Persistencia.AlumnoData; 
import Modelo.Alumno;          
import javax.swing.JOptionPane; 
/**
 *
 * @author vanne
 */
public class BajaAltaLogicaAlumno extends javax.swing.JInternalFrame {
    private AlumnoData alumnoData;
    private Alumno alumnoActual = null;
    /**
     * Creates new form BajaAltaLogicaAlumno
     */
    public BajaAltaLogicaAlumno(AlumnoData ad) {
        initComponents();
        initComponents();
        this.alumnoData = ad; 
        // Inhabilita los botones de acción hasta que se busque un alumno
        jBbaja.setEnabled(false); 
        jBalta.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBbuscar = new javax.swing.JButton();
        jBbaja = new javax.swing.JButton();
        jBalta = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 153));
        jLabel1.setText("Baja/Alta logica ");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("ID.Alumno :");

        jBbuscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBbuscar.setText("Buscar");
        jBbuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 3));
        jBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarActionPerformed(evt);
            }
        });

        jBbaja.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBbaja.setText("Baja");
        jBbaja.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 3));
        jBbaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbajaActionPerformed(evt);
            }
        });

        jBalta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBalta.setText("Alta");
        jBalta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 3));
        jBalta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaltaActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jBbuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jBbaja, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jBalta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 112, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jBbaja, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jBalta, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBbuscar)
                    .addComponent(jBbaja)
                    .addComponent(jBalta))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBbajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbajaActionPerformed
        // TODO add your handling code here:
        if (alumnoActual == null || !alumnoActual.getEstado()) {
            JOptionPane.showMessageDialog(this, "Primero debe buscar un alumno ACTIVO para dar de baja.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            if (JOptionPane.showConfirmDialog(this, "¿Está seguro de dar de BAJA (Inactivar) al alumno?", "Confirmar Baja Lógica", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                
                // Llamar al método de la capa de datos
                alumnoData.borrarAlumnoLogico(alumnoActual.getIdAlumno()); // Asume que este método cambia el estado a 'false'
                
                JOptionPane.showMessageDialog(this, "Alumno dado de BAJA (Inactivo) correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                
                // Resetear la vista
                jTextField1.setText("");
                alumnoActual = null;
                jBbaja.setEnabled(false);
                jBalta.setEnabled(false);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al intentar dar de baja: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBbajaActionPerformed

    private void jBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarActionPerformed
        // TODO add your handling code here:
      try {
            int idBusqueda = Integer.parseInt(jTextField1.getText());
            alumnoActual = alumnoData.buscarAlumno(idBusqueda); // Usamos buscarAlumno por ID

            if (alumnoActual != null) {
                String estado = alumnoActual.getEstado() ? "ACTIVO" : "INACTIVO";
                JOptionPane.showMessageDialog(this, 
                    "Alumno encontrado: " + alumnoActual.getNombre() + " " + alumnoActual.getApellido() + 
                    "\nEstado Actual: " + estado, 
                    "Búsqueda Exitosa", JOptionPane.INFORMATION_MESSAGE);

                // Habilitar/Deshabilitar botones de Baja/Alta
                if (alumnoActual.getEstado()) {
                    jBbaja.setEnabled(true);  // Si está activo, puede dar de BAJA
                    jBalta.setEnabled(false);
                } else {
                    jBbaja.setEnabled(false);
                    jBalta.setEnabled(true);  // Si está inactivo, puede dar de ALTA
                }
                
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró ningún alumno con el ID ingresado.", "Error de Búsqueda", JOptionPane.ERROR_MESSAGE);
                alumnoActual = null;
                jBbaja.setEnabled(false);
                jBalta.setEnabled(false);
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un ID válido (número entero).", "Error de Entrada", JOptionPane.ERROR_MESSAGE);
            alumnoActual = null;
            jBbaja.setEnabled(false);
            jBalta.setEnabled(false);
        }   
    }//GEN-LAST:event_jBbuscarActionPerformed

    private void jBaltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaltaActionPerformed
        // TODO add your handling code here:
        if (alumnoActual == null || alumnoActual.getEstado()) {
            JOptionPane.showMessageDialog(this, "Primero debe buscar un alumno INACTIVO para dar de alta.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            if (JOptionPane.showConfirmDialog(this, "¿Está seguro de dar de ALTA (Activar) al alumno?", "Confirmar Alta Lógica", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                
                // LLAMADA A MÉTODO DE ALTA LÓGICA (Estado=1)
                alumnoData.activarAlumno(alumnoActual.getIdAlumno()); 
                
                JOptionPane.showMessageDialog(this, "Alumno dado de ALTA (Activo) correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                
                // Resetear la vista
                jTextField1.setText("");
                alumnoActual = null;
                jBbaja.setEnabled(false);
                jBalta.setEnabled(false);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al intentar dar de alta: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBaltaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBalta;
    private javax.swing.JButton jBbaja;
    private javax.swing.JButton jBbuscar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
