package Vista;

import modelo.Conexion;
import Persistencia.AlumnoData;
import Persistencia.MateriaData;
import Persistencia.InscripcionData;

public class SGULP extends javax.swing.JFrame {

    private AlumnoData alumnoData;
    private MateriaData materiaData;
    private InscripcionData inscripcionData;
    private Conexion conexion;

    /**
     * Creates new form NewJFrame
     */
    public SGULP(AlumnoData ad, MateriaData md, InscripcionData id) { 
        initComponents();
        this.setLocationRelativeTo(null);

        this.alumnoData = ad;
        this.materiaData = md;
        this.inscripcionData = id;
        /*try {
            // **logica de inicializacion**
            conexion = new Conexion("jdbc:mariadb://localhost:3306/sgulp", "root", ""); 
            alumnoData = new AlumnoData(conexion);
            materiaData = new MateriaData(conexion);
            inscripcionData = new InscripcionData(conexion);
            
        } catch (Exception ex) {
            System.err.println("Error Critico al iniciar la aplicación. La conexión o las capas de datos fallaron: " + ex.getMessage());
        }*/
    }

    /*public SGULP(AlumnoData ad, MateriaData md, InscripcionData id) { 
        initComponents();
        this.setLocationRelativeTo(null);
        this.alumnoData = ad; 
        this.materiaData = md; 
        this.inscripcionData = id; 
    
        try {
            // 
            conexion = new Conexion("jdbc:mariadb://localhost:3306/sgulp", "root", ""); 
            alumnoData = new AlumnoData(conexion);
        } catch (Exception ex) {
            // Manejo de errores de conexión/inicialización
            System.err.println("Error al iniciar la Conexión o AlumnoData: " + ex.getMessage());
            // Si la conexión falla, es un error grave.
        }
    
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmalumno = new javax.swing.JMenuItem();
        jmateria = new javax.swing.JMenuItem();
        jminscripcion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        jMenu1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jMenu1.setForeground(new java.awt.Color(0, 0, 153));
        jMenu1.setText("Vistas");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jmalumno.setText("Vista Alumno");
        jmalumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmalumnoActionPerformed(evt);
            }
        });
        jMenu1.add(jmalumno);

        jmateria.setText("Vista Materia");
        jmateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmateriaActionPerformed(evt);
            }
        });
        jMenu1.add(jmateria);

        jminscripcion.setText("Vista Inscripcion");
        jminscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jminscripcionActionPerformed(evt);
            }
        });
        jMenu1.add(jminscripcion);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jmalumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmalumnoActionPerformed
        // TODO add your handling code here:
        // 🔑 VALIDACIÓN DE SEGURIDAD: Verifica si la conexión falló al inicio.
        if (alumnoData == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error Crítico: No se pudo establecer la conexión a la base de datos (alumnoData es NULL).",
                    "Error de Inicialización",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return; // Si es nulo, detenemos la ejecución aquí.
        }
        for (javax.swing.JInternalFrame frame : jDesktopPane1.getAllFrames()) {
            if (frame instanceof VistaAlumno) {
                frame.toFront();
                return;
            }
        }

        // Abre la vista de Alumno y le pasa la capa de datos
        VistaAlumno va  = new VistaAlumno(alumnoData);
        jDesktopPane1.add(va);
        va.setVisible(true);
        va.moveToFront();


    }//GEN-LAST:event_jmalumnoActionPerformed

    private void jmateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmateriaActionPerformed
        // TODO add your handling code here:
        if (materiaData == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: No se inicializaron los datos (materiaData es NULL).", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 2. Crear una nueva instancia de la vista de Materia, pasándole los datos.
        VistaMateria vm = new VistaMateria(materiaData);

        // 3. Añadirla al escritorio y hacerla visible
        jDesktopPane1.add(vm);
        vm.setVisible(true);
        vm.toFront();
    }//GEN-LAST:event_jmateriaActionPerformed

    private void jminscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jminscripcionActionPerformed

        // Crear la vista de inscripción pasándole la capa de datos
        VistaInscripcion vi = new VistaInscripcion(alumnoData, materiaData, inscripcionData);

        // Agregarla al escritorio (JDesktopPane) del JFrame principal
        jDesktopPane1.add(vi);

        // Mostrar la ventana interna
        vi.setVisible(true);

        // Opcional: traerla al frente
        vi.toFront();
    }//GEN-LAST:event_jminscripcionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmalumno;
    private javax.swing.JMenuItem jmateria;
    private javax.swing.JMenuItem jminscripcion;
    // End of variables declaration//GEN-END:variables
}
