/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Persistencia.AlumnoData;
import javax.swing.JDesktopPane;
/**
 *
 * @author vanne
 */
public class VistaAlumno extends javax.swing.JInternalFrame {
    private AlumnoData alumnoData;
    
    
    public VistaAlumno(AlumnoData ad) {
        initComponents();
        this.alumnoData = ad;
    }
    /**
     * Creates new form VistasAlumno
     */
    public VistaAlumno(){
        initComponents();
    }

   // VistaAlumno(AlumnoData alumnoData) {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
   // }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBinsertar = new javax.swing.JButton();
        jBactualizar = new javax.swing.JButton();
        jBbajaalta = new javax.swing.JButton();
        jBmostrartodo = new javax.swing.JButton();
        jBborrar = new javax.swing.JButton();

        jBinsertar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBinsertar.setForeground(new java.awt.Color(102, 0, 153));
        jBinsertar.setText("Insertar");
        jBinsertar.setBorder(new javax.swing.border.MatteBorder(null));
        jBinsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBinsertarActionPerformed(evt);
            }
        });

        jBactualizar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBactualizar.setForeground(new java.awt.Color(102, 0, 153));
        jBactualizar.setText("Actualizar");
        jBactualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBactualizarActionPerformed(evt);
            }
        });

        jBbajaalta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBbajaalta.setForeground(new java.awt.Color(102, 0, 153));
        jBbajaalta.setText("Baja/AltaLogica");
        jBbajaalta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBbajaalta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbajaaltaActionPerformed(evt);
            }
        });

        jBmostrartodo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBmostrartodo.setForeground(new java.awt.Color(102, 0, 153));
        jBmostrartodo.setText("Mostrar Todos");
        jBmostrartodo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBmostrartodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmostrartodoActionPerformed(evt);
            }
        });

        jBborrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBborrar.setForeground(new java.awt.Color(204, 0, 0));
        jBborrar.setText("Borrar");
        jBborrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        jBborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBborrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBinsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBbajaalta)
                    .addComponent(jBborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBmostrartodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBactualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBinsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBmostrartodo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBbajaalta, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jBborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBinsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBinsertarActionPerformed
        // TODO add your handling code here:
        InsertarAlumno vi = new InsertarAlumno(this.alumnoData); 
        this.getDesktopPane().add(vi);
        vi.setVisible(true);
        vi.moveToFront();
    }//GEN-LAST:event_jBinsertarActionPerformed

    private void jBborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBborrarActionPerformed
        // TODO add your handling code here:
        BorrarAlumno vb = new BorrarAlumno(this.alumnoData); 
        this.getDesktopPane().add(vb);
        vb.setVisible(true);
        vb.moveToFront();
    }//GEN-LAST:event_jBborrarActionPerformed

    private void jBactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBactualizarActionPerformed
        // TODO add your handling code here:
        ActualizarAlumno va = new ActualizarAlumno(this.alumnoData); 
        this.getDesktopPane().add(va);
        va.setVisible(true);
        va.moveToFront();
    }//GEN-LAST:event_jBactualizarActionPerformed

    private void jBbajaaltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbajaaltaActionPerformed
        // TODO add your handling code here:
        BajaAltaLogicaAlumno vbal = new BajaAltaLogicaAlumno(this.alumnoData); 
        this.getDesktopPane().add(vbal);
        vbal.setVisible(true);
        vbal.moveToFront();
    }//GEN-LAST:event_jBbajaaltaActionPerformed

    private void jBmostrartodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmostrartodoActionPerformed
        // TODO add your handling code here:
        MostrarTodoAlumno vta = new MostrarTodoAlumno(this.alumnoData); 
        this.getDesktopPane().add(vta);
        vta.setVisible(true);
        vta.moveToFront();
    }//GEN-LAST:event_jBmostrartodoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBactualizar;
    private javax.swing.JButton jBbajaalta;
    private javax.swing.JButton jBborrar;
    private javax.swing.JButton jBinsertar;
    private javax.swing.JButton jBmostrartodo;
    // End of variables declaration//GEN-END:variables
}
